global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: telegram
    webhook_configs:
      - url: 'http://alertmanager-bot:8080'  # Must match your docker-compose service name and bot port
        send_resolved: true
