global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.121.26:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.121.26:9090']

  - job_name: 'node_exporter_kali1'
    static_configs:
      - targets: ['192.168.121.26:9100']

  - job_name: 'node_exporter_kali2'
    static_configs:
      - targets: ['192.168.121.25:9100']