global:
  scrape_interval: 15s


rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['{$NODE_SERVER_1}:{$PROMETHEUS_PORT}']

  - job_name: 'node_exporter_kali1'
    static_configs:
      - targets: ['{$NODE_SERVER_1}:{$NODE_EXPORTER_PORT}']

  - job_name: 'node_exporter_kali2'
    static_configs:
      - targets: ['{$NODE_SERVER_2}:{$NODE_EXPORTER_PORT}']

