global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.121.26:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.121.26:9090']

  - job_name: 'node_exporter_kali1'
    static_configs:
      - targets: ['192.168.121.26:9100']

  - job_name: 'node_exporter_kali2'
    static_configs:
      - targets: ['192.168.121.25:9100']

  - job_name: 'cadvisor-server-1'
    static_configs:
      - targets: ['192.168.121.26:8080']

  - job_name: 'cadvisor-server-2'
    static_configs:
      - targets: ['192.168.121.25:8080']

  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
          - 192.168.121.26
          - 192.168.121.25
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox_tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - 192.168.121.26:22
          - 192.168.121.25:22
          - google.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://google.com
          - http://github.com
          - http://192.168.121.26:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

